name: Primer workflow GH-200

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
        environment:
            description: 'Entorno de ejecución'
            required: true
            type: choice
            options:
             - test
             - pre

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Validar proyecto con action local
        id: test_project
        uses: ./.github/actions/test-project
        with:
          node-version: '24'
        
      - name: Mostrar resultado de la action
        run: |
          echo "Resultado de la action: ${{ steps.test_project.outputs.result }}"
          
  info:
    needs: validate
    runs-on: ubuntu-latest

    steps:
     - name: Mostrar información del runner
       run: |
            pwd
            node --version
            echo "$GITHUB_WORKSPACE"        
            
     - name: Mostrar entorno seleccionado
       run: | 
            echo "Entorno seleccionado: ${{ inputs.environment }}"