name: Primer workflow GH-200

on:
  push:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar tests
        run: npm test
  info:
    runs-on: ubuntu-latest

    steps:
     - name: Mostrar información del runner
       run: |
            pwd
            node --version
            echo "$GITHUB_WORKSPACE"        