name: CD

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Mostrar despliegue
        run: |
          echo "Desplegando en staging"

      - name: Mostrar entorno configurado
        run: |
          echo "Entorno configurado: ${{ vars.APP_ENV }}"