name: "Instalacion YAML"

description: "Este workflow se encarga de instalar las dependencias y construir el proyecto utilizando npm y webpack."

on:
  workflow_dispatch:

jobs:
  instalacion:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Instalar dependencias
        run: npm install

      - name: Construir aplicación
        run: npm run build