name: GitHub Script

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read
  
jobs:
  script:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar GitHub Script
        uses: actions/github-script@v7
        with:
          script: |
            core.info(`Owner: ${context.repo.owner}`)
            core.info(`Repo: ${context.repo.repo}`)
            core.info(`Repo completo: ${context.repo.owner}/${context.repo.repo}`)