name: Hello JS
description: Action JavaScript de ejemplo para GH-200

inputs:
  name:
    description: 'Nombre a saludar'
    required: true

outputs:
  greeting:
    description: 'Mensaje de saludo'

runs:
  using: node20
  main: index.js